### ISSUE TITLE
sharing of your Tachometer project

### ISSUE THREAD

**Issue by aeonSolutions** [carneeki/Tachometer#1]
hi @carneeki 
great work!  👍👍👍👍👍

i'm sharing your project on my own "Open Hardware Electronics for the Volvo P2 platform"
[https://github.com/aeonSolutions/AeonLabs-AI-Volvo-MKII-Open-Hardware/wiki/Programming-the-Instruments-Cluster](https://github.com/aeonSolutions/AeonLabs-AI-Volvo-MKII-Open-Hardware/wiki/Programming-the-Instruments-Cluster)

![image](https://github.com/carneeki/Tachometer/assets/7936768/b72c03af-663e-41fc-808a-3abfb7192128)

**Comment by carneeki** [comment]
Good luck with your project, it looks great!

**Comment by aeonSolutions** [comment]
thank you.
